{
    'name': 'Ait',
    'depends': ['project', 'account', 'hr_timesheet'],
    'version': '0.1',
    'data': [
        'views/c_ait_discipline_views.xml',
        'views/account_analytic_line_views.xml',
        'views/project_task_views.xml',
        'views/project_edit_views.xml',
        'views/c_ait_employment_status_views.xml',
        'views/hr_employee_views.xml',
        'views/c_ait_work_perspective_views.xml',
        'views/c_ait_contract_views.xml',
        'views/c_ait_tariff_views.xml',
        'views/c_ait_plan_views.xml',
        'views/c_ait_plan_line_views.xml',
        'views/c_ait_plan_type_views.xml',
        'report/account_analytic_line_report_views.xml',
        'report/working_hours_per_project_report_template.xml',
        'report/project_task_report_views.xml',
        'wizard/c_ait_create_invoice_wizard_views.xml',
        'views/c_ait_reservation_views.xml',
        'security/ir.model.access.csv',
    ],
    'post_init_hook': 'report.post_init_hook',
    'installable': True,
    'license': 'LGPL-3',
}